env_id: ALE/Pong-v5

total_steps: 10_000_000
train_frequency_steps: 4

seed: 2137

replay_warmup_steps: 50_000
replay_capacity: 100_000

batch_size: 32
learning_rate: 0.0001

epsilon_start: 1.0
epsilon_end: 0.01
epsilon_decay_steps: 1_000_000

target_sync_interval_steps: 10_000
reward_clip: 1.0
gamma: 0.99

device: cpu
policy_dir: null

eval_interval_steps: 250_000
eval_episodes: 10

log_interval_steps: 10_000
episode_window_size: 100
loss_window_size: 100
wandb_project: pong
wandb_mode: online
